dataconf = configuration_data()
dataconf.set('BACKGROUNDDIR', backgrounddir)
dataconf.set('datadir', datadir)

backgrounds = [
  'adwaita-d.jxl',
  'adwaita-l.jxl',
  'adwaita-thumbnail.png',
  'amber-d.jxl',
  'amber-l.jxl',
  'amber-thumbnail.png',
  'balls-d.jxl',
  'balls-l.jxl',
  'balls-thumbnail.png',
  'blendpills-d.jxl',
  'blendpills-l.jxl',
  'blendpills-thumbnail.png',
  'blobs-d.svg',
  'blobs-l.svg',
  'blobs-thumbnail.png',
  'curvaturingster-d.jxl',
  'curvaturingster-l.jxl',
  'curvaturingster-thumbnail.png',
  'curvy-d.jxl',
  'curvy-l.jxl',
  'curvy-thumbnail.png',
  'dithered-sun-d.jxl',
  'dithered-sun-l.jxl',
  'dithered-sun-thumbnail.png',
  'drool-d.svg',
  'drool-l.svg',
  'drool-thumbnail.png',
  'fold-d.jxl',
  'fold-l.jxl',
  'fold-thumbnail.png',
  'glass-chip-d.jxl',
  'glass-chip-l.jxl',
  'glass-chip-thumbnail.png',
  'glass-stripes-d.jxl',
  'glass-stripes-l.jxl',
  'glass-stripes-thumbnail.png',
  'lcd-rainbow-d.jxl',
  'lcd-rainbow-l.jxl',
  'lcd-rainbow-thumbnail.png',
  'map-d.svg',
  'map-l.svg',
  'map-thumbnail.png',
  'morphogenesis-d.svg',
  'morphogenesis-l.svg',
  'morphogenesis-thumbnail.png',
  'pills-d.jxl',
  'pills-l.jxl',
  'pills-thumbnail.png',
  'pixel-pusher-d.jxl',
  'pixel-pusher-l.jxl',
  'pixel-pusher-thumbnail.png',
  'pixels-d.jxl',
  'pixels-l.jxl',
  'pixels-thumbnail.png',
  'progress-d.jxl',
  'progress-l.jxl',
  'progress-thumbnail.png',
  'sheet-d.jxl',
  'sheet-l.jxl',
  'sheet-thumbnail.png',
  'symbolic-d.jxl',
  'symbolic-l.jxl',
  'symbolic-thumbnail.png',
  'tarka-d.jxl',
  'tarka-l.jxl',
  'tarka-thumbnail.png',
  'tarkov-pills-d.jxl',
  'tarkov-pills-l.jxl',
  'tarkov-pills-thumbnail.png',
  'tubes-d.jxl',
  'tubes-l.jxl',
  'tubes-thumbnail.png',
  'vnc-d.png',
  'vnc-l.png',
  'vnc-thumbnail.png',
]

install_data(backgrounds, install_dir: backgrounddir)

foreach metadata : [
  'adwaita.xml',
  'amber.xml',
  'balls.xml',
  'blendpills.xml',
  'blobs.xml',
  'curvaturingster.xml',
  'curvy.xml',
  'dithered-sun.xml',
  'drool.xml',
  'fold.xml',
  'glass-chip.xml',
  'glass-stripes.xml',
  'lcd-rainbow.xml',
  'map.xml',
  'morphogenesis.xml',
  'pills.xml',
  'pixel-pusher.xml',
  'pixels.xml',
  'progress.xml',
  'sheet.xml',
  'symbolic.xml',
  'tarka.xml',
  'tarkov-pills.xml',
  'tubes.xml',
  'vnc.xml',
]
  configure_file(
    input: metadata + '.in',
    output: metadata,
    configuration: dataconf,
    install: true,
    install_dir: metadatadir
  )
endforeach
